from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from rest_framework import status
from rest_framework.response import Response

def getWines(request):
    return HttpResponse("""
    [{  "wine_id": 0,
		"wine_name": "Cielo e Terra Pinot Grigio 2020",
		"wine_alcohol": 12,
		"wine_type": "white",
		"wine_year": 2020,
		"wine_country": "delle Venezie, Italien",
		"wine_price": 3.95,
		"wine_tastes": [
			"Grüner Apfel",
			"Apfel",
			"Pfirsich",
			"Birne",
			"Melone",
			"Nektarine",
			"Aprikose",
			"Quitte",
			"Honigmelone",
			"Steinfrucht",
			"Gelber Apfel",
			"Cantaloupe-Melone",
			"Weißer Pfirsich",
			"Grüne Melone",
			"Zitrone",
			"Zitrone",
			"Grapefruit",
			"Limette",
			"Mandarine",
			"Orange",
			"Zitruswürze",
			"Zitronenschale",
			"Zitronenwürze",
			"Ananas",
			"Tropisch",
			"Litschi",
			"Honig",
			"Mineralien",
			"Stein",
			"Leder",
			"Ingwer",
			"Teer",
			"Champignon",
			"Banane",
			"Käse",
			"Creme",
			"Yoga-Studio",
			"Butter",
			"Vanille",
			"Karamell",
			"Eiche",
			"Stroh",
			"Gras",
			"Stachelbeere",
			"Geißblatt",
			"Zitronenblüte",
			"Lavendel",
			"Walnuss",
			"Mandel",
			"Nussig",
			"Toast",
			"Cranberry",
			"Kirsche",
			"Erdbeere",
			"Getrocknete Aprikose",
			"Pflaume"
		]},
		{
		"wine_id": 1,
		"wine_name": "Antares Sauvignon Blanc 2020",
		"wine_alcohol": 12,
		"wine_type": "white",
		"wine_year": 2020,
		"wine_country": "Central Valley, Chile",
		"wine_price": 4.44,
		"wine_tastes": [
			"Zitrone",
			"Grapefruit",
			"Limette",
			"Zitronenwürze",
			"Limettenmark",
			"Tropisch",
			"Ananas",
			"Passionsfrucht",
			"Kiwi",
			"Guave",
			"Melone",
			"Apfel",
			"Aprikose",
			"Birne",
			"Steinfrucht",
			"Grüner Apfel",
			"Pfirsich",
			"Nektarine",
			"Gras",
			"Stroh",
			"Stachelbeere",
			"Spargel",
			"Grüne Paprika",
			"Tomate",
			"Honig",
			"Stein",
			"Mineralien",
			"Leder",
			"Asche",
			"Saline",
			"Butter",
			"Vanille",
			"Kirsche",
			"Wassermelone",
			"Käse",
			"Pfeffer",
			"Schwarze Johannisbeere",
			"Geißblatt"
		]}
	]
    """)
